### ISSUE TITLE
Ustawienia prywatności nie działają.

### ISSUE THREAD

**Issue by Arturro43** [Mensix/SpisSekcji#17]
https://i.imgur.com/1Az6QDF.gif

**Comment by Mensix** [comment]
AdBlock/uBlock blokuje.

**Comment by Mensix** [comment]
Poza tym w sumie nie wiem czy są wymagane aż takie kroki tylko do wyrażenia zgody na używanie danych zwiedzających użytkowników do Google Analytics (nie mam włączonych żadnych powiązanych usług typu reklamy czy coś).
