### ISSUE TITLE
Hej hej hej

### ISSUE THREAD

**Issue by makoteq** [Mensix/SpisSekcji#25]
Jest szansa na przyłączenie się do projektu?
Widzę że używasz Vue.js wiec mi to bardzo odpowiada

**Comment by Mensix** [comment]
Proszę bardzo, jak masz jakieś pomysły jak ulepszyć stronkę lub kod to proszę słać PR-y lub błędy (issues, nie wiem jak to przetłumaczyć) :)

**Comment by makoteq** [comment]
da radę się zgadać na FB bo mam parę pytań? @Mensix

**Comment by Mensix** [comment]
można jak najbardziej

**Comment by makoteq** [comment]
@Mensix wysłałem ci zapro - "MAciej Kotowski"
